/*
TODO: Set up signup and login routes
TODO: Set up hosting on Vercel
TODO: Research how to set up advertising



GLOBAL TODO: BETTER MOVIE AND TV SHOW DETAIL PAGE
GLOBAL TODO: USER PROFILE PAGE
GLOBAL TODO: USER BASED FEATURES (WATCHLIST, FAVORITES, REVIEWS, ETC)
GLOBAL TODO: DECIDE AND IMPLEMENT USER RELATIONSHIPS (FOLLOWING/FRIENDS/ETC)
GLOBAL TODO: SCORING SYSTEM
 */